site_name: Gateway Documentation
site_url: "https://bchwtz.github.io/bchwtz-gateway/"

theme:
  name: "material"
  features:
    - content.code.annotate
    - content.code.copy

plugins:
  - mkdocstrings
  - search
  - minify:
      minify_html: true
  - enumerate-headings
  - autorefs

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - sane_lists

nav:
  - Introduction: index.md
  - Getting Started:
    - Initial Setup:
      - sensor_setup.md
      - raspi_setup.md
      - gateway_setup.md
    - go_cli.md
    - JupyterHub.md
    - PyCharm.md
    - GettingStartedPackage.md
  - Documentation:
    - Sensor.md
    - ExternalFlashIntegration.md
    - Gateway.md
    - Backend.md
    - BLEGATTMessages.md
    - MessageObjects.md
    - practical_guide.md
  - Reference:
    - Gateway Library:
      - bluetooth-python-library/gateway_ref.md
      - bluetooth-python-library/config_ref.md
      - bluetooth-python-library/hub_ref.md
      - bluetooth-python-library/tag_ref.md
      - bluetooth-python-library/sensor_ref.md
      - bluetooth-python-library/ble_conn_ref.md
    - Global Architecture:
      - global_architecture/mqtt_messages.md
      - global_architecture/docker_architecture.md
      - global_architecture/development_principles.md
    - Additional Microservices:
      - CLI: go-services/cli_ref.md
      - Dumper: go-services/dumper_ref.md
    - Examples:
      - Demos: 
        - Overview: demos_overview.md
        - Analyse Heartbeat: analyse_heartbeats_ref.md
        - Time Demo: current_time_demo_ref.md
        - Heartbeat Demo: get_set_heartbeat_ref.md
        - Acceleration Log Demo: demo_get_acc_log_ref.md
        - Connect and use MongoDB: demo_mongodb_ref.md
        - Convert acceleration JSON and find peaks: demo_convert_peak.md
        - Change Config: demo_set_config_ref.md
        - Get acceleration log: demo_acc_log_cli.md
      - Tests:
        - Test Documentation: bluetooth-python-library/test-documentation.md
        - Hub Tests: bluetooth-python-library/hub_test_ref.md
        - Tag Test: bluetooth-python-library/tag_test_ref.md
        - Tag Config Tests: bluetooth-python-library/tag_config_test_ref.md
    - Further tutorials:
      - git_installation_on_raspberry.md
      - MKDocs: documentation_ref.md
      - Useful tips: useful_tips.md
  - Current bugs: current_bugs.md
  - To Do:
    - todo_sensor.md
    - todo_gateway.md
    - todo_backend.md
  - Appendix:
    - Contributors.md
    - CommercialApplications.md
    - Merging.md
    - SystemInfo.md
  - DontDo.md
  - Do.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bchwtz/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
